name: Build and Compile

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone target repository
      run: git clone https://github.com/Lauriethefish/ModsBeforeFriday.git

    - name: Set up Rust
      uses: moonrepo/setup-rust@v1
      with:
        rust-version: '1.77' # Specify the Rust version used in the project

    - name: Build mbf-agent
      run: |
        cd ModsBeforeFriday/mbf-agent
        cargo build --release

    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: |
          ModsBeforeFriday/mbf-agent/target/release/
          ModsBeforeFriday/mbf-res-man/target/release/
