name: Compile mbf-res-man

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        repository: Lauriethefish/ModsBeforeFriday
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install dependencies and compile
      run: cargo build --release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mbf-res-man
        path: target/release/
